# Generated by Django 3.1.4 on 2021-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=225)),
                ('phone_no', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
