# Generated by Django 3.1.4 on 2021-01-02 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
